# Generated by Django 5.0.2 on 2024-04-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about'),
        ),
    ]
