# Generated by Django 5.0.2 on 2024-04-16 07:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'author')},
        ),
    ]
